import Head from 'next/head'
import { useUser } from '@/hooks/useUser'
import { useAuthFetch } from '@/hooks/useAuthFetch'
export default function Home() {
  const { logout } = useUser();
  const { data, loading, error} = useAuthFetch("http://localhost:3000/api/users/logged");
  if(loading){
    return <h1>Loading...</h1>
  }
  if(error){
    return <h1>Error</h1>
  }
  console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Hola
        </h1>
        <button onClick={logout}>
          Logout
        </button>
      </main>
    </>
  )
}
